# Generated by Django 6.0.1 on 2026-01-09 18:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Place/Location name (e.g., Kathmandu, Biratnagar)', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this place is active and accessible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft deleted - data remains but place is inaccessible')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When the place was soft deleted', null=True)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Super admin who deleted the place', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='places_plac_slug_1928e6_idx'), models.Index(fields=['is_active'], name='places_plac_is_acti_7fcf18_idx'), models.Index(fields=['is_deleted'], name='places_plac_is_dele_e0f0d1_idx'), models.Index(fields=['created_at'], name='places_plac_created_6fc9cf_idx')],
            },
        ),
    ]
