import 'package:dio/dio.dart';
import 'package:flutter/foundation.dart';
import 'package:sewa_web/core/constants/api_endpoints.dart';
import 'package:sewa_web/core/errors/exceptions.dart';
import 'package:sewa_web/core/network/api_client.dart';
import 'package:sewa_web/features/auth/data/models/ministry_model.dart';
import 'package:sewa_web/features/auth/domain/entities/ministry.dart';
import 'package:sewa_web/features/super_admin/data/models/place_filter_option_model.dart';
import 'package:sewa_web/features/super_admin/domain/entities/place_filter_option.dart';

/// Remote data source for Ministry operations
/// Handles API calls to fetch and manage ministries
abstract class MinistryRemoteDataSource {
  /// Fetch all places for filter dropdown
  /// API: GET /ministry/admin/places/
  Future<List<PlaceFilterOption>> getPlacesForFilter();

  /// Fetch all ministries for Super Admin (requires auth)
  /// API: GET /api/tenants/admin/
  /// Now supports optional place filter parameter
  Future<List<Ministry>> getAdminMinistries({
    String? place,
    String? status,
    String? search,
    int? page,
    int? pageSize,
  });

  /// Get ministry details by ID (Super Admin)
  /// API: GET /api/tenants/admin/{id}/
  Future<Ministry> getMinistryById(String id);

  /// Create a new ministry (Super Admin)
  /// API: POST /api/tenants/admin/
  /// placeId is required - ministry MUST belong to a place
  /// email and password are required for ministry admin login credentials
  /// Note: slug is auto-generated by backend from ministry name
  Future<Ministry> createMinistry({
    required String placeId,
    required String name,
    required String email,
    required String password,
    String? description,
    String? phone,
    String? address,
    String? website,
    Uint8List? logoBytes,
    String? logoFileName,
  });

  /// Update ministry (Super Admin)
  /// API: PATCH /api/tenants/admin/{id}/
  Future<Ministry> updateMinistry({
    required String id,
    String? name,
    String? description,
    String? email,
    String? phone,
    String? address,
    String? website,
    Uint8List? logoBytes,
    String? logoFileName,
  });

  /// Delete ministry (Super Admin)
  /// API: DELETE /api/tenants/admin/{id}/
  Future<void> deleteMinistry(String id);

  /// Activate ministry (Super Admin)
  /// API: POST /api/tenants/admin/{id}/activate/
  Future<Ministry> activateMinistry(String id);

  /// Suspend ministry (Super Admin)
  /// API: POST /api/tenants/admin/{id}/suspend/
  Future<Ministry> suspendMinistry(String id, {String? reason});

  /// Get list of deleted ministries (Super Admin)
  /// API: GET /api/tenants/admin/deleted/
  Future<List<Ministry>> getDeletedMinistries();

  /// Restore a soft-deleted ministry (Super Admin)
  /// API: POST /api/tenants/admin/{id}/restore/
  Future<Ministry> restoreMinistry(String id);

  /// Permanently delete ministry (Super Admin) - cannot be undone
  /// API: POST /api/tenants/admin/{id}/hard-delete/
  Future<void> hardDeleteMinistry(String id);

  /// Reset ministry admin password (Super Admin)
  /// API: POST /api/tenants/admin/{id}/reset-password/
  Future<void> resetMinistryPassword(String id, String newPassword);

  // ============================================
  // MINISTRY SELF-MANAGEMENT (Staff users)
  // ============================================

  /// Get own ministry details (Ministry Admin)
  /// API: GET /api/tenants/me/
  Future<Ministry> getMyMinistry();

  /// Update own ministry profile (Ministry Admin)
  /// API: PATCH /api/tenants/me/
  /// Note: Ministry admins can only update limited fields (description, phone, address, website, logo)
  Future<Ministry> updateMyMinistry({
    String? description,
    String? phone,
    String? address,
    String? website,
    Uint8List? logoBytes,
    String? logoFileName,
  });
}

class MinistryRemoteDataSourceImpl implements MinistryRemoteDataSource {
  final ApiClient apiClient;

  MinistryRemoteDataSourceImpl({required this.apiClient});

  @override
  Future<List<PlaceFilterOption>> getPlacesForFilter() async {
    try {
      final responseData = await apiClient.get(
        ApiEndpoints.ministriesPlacesFilter,
      );

      if (responseData['success'] != true) {
        throw ServerException(
          message: responseData['error'] ?? 'Failed to fetch places',
        );
      }

      final data = responseData['data'] as List<dynamic>? ?? [];
      return data
          .map(
            (json) =>
                PlaceFilterOptionModel.fromJson(json as Map<String, dynamic>),
          )
          .toList();
    } on DioException catch (e) {
      throw ServerException(message: _handleDioError(e));
    } catch (e) {
      if (e is ServerException) rethrow;
      throw ServerException(message: e.toString());
    }
  }

  @override
  Future<List<Ministry>> getAdminMinistries({
    String? place,
    String? status,
    String? search,
    int? page,
    int? pageSize,
  }) async {
    try {
      final queryParams = <String, dynamic>{};
      if (place != null && place.isNotEmpty) queryParams['place'] = place;
      if (status != null) queryParams['status'] = status;
      if (search != null) queryParams['search'] = search;
      if (page != null) queryParams['page'] = page;
      if (pageSize != null) queryParams['page_size'] = pageSize;

      final responseData = await apiClient.get(
        ApiEndpoints.adminMinistriesList,
        queryParameters: queryParams.isNotEmpty ? queryParams : null,
      );

      if (responseData['success'] != true) {
        throw ServerException(
          message: responseData['error'] ?? 'Failed to fetch ministries',
        );
      }

      final data = responseData['data'] as List<dynamic>? ?? [];
      return data
          .map((json) => MinistryModel.fromJson(json as Map<String, dynamic>))
          .toList();
    } on DioException catch (e) {
      throw ServerException(message: _handleDioError(e));
    } catch (e) {
      if (e is ServerException) rethrow;
      throw ServerException(message: e.toString());
    }
  }

  @override
  Future<Ministry> getMinistryById(String id) async {
    try {
      final responseData = await apiClient.get(
        ApiEndpoints.adminMinistryDetail(id),
      );

      if (responseData['success'] != true) {
        throw ServerException(
          message: responseData['error'] ?? 'Failed to fetch ministry',
        );
      }

      return MinistryModel.fromJson(responseData['data']);
    } on DioException catch (e) {
      throw ServerException(message: _handleDioError(e));
    } catch (e) {
      if (e is ServerException) rethrow;
      throw ServerException(message: e.toString());
    }
  }

  @override
  Future<Ministry> createMinistry({
    required String placeId,
    required String name,
    required String email,
    required String password,
    String? description,
    String? phone,
    String? address,
    String? website,
    Uint8List? logoBytes,
    String? logoFileName,
  }) async {
    try {
      // Note: slug is auto-generated by backend from ministry name
      // Do NOT send slug, status, or settings - they have backend defaults
      final formData = FormData.fromMap({
        'place': placeId, // Required - ministry must belong to a place
        'name': name,
        'email': email,
        'password': password,
        if (description != null) 'description': description,
        if (phone != null) 'phone': phone,
        if (address != null) 'address': address,
        if (website != null) 'website': website,
        if (logoBytes != null && logoFileName != null)
          'logo': MultipartFile.fromBytes(logoBytes, filename: logoFileName),
      });

      final responseData = await apiClient.post(
        ApiEndpoints.adminMinistryCreate,
        data: formData,
        options: Options(contentType: 'multipart/form-data'),
      );

      if (responseData['success'] != true) {
        throw ServerException(
          message: responseData['error'] ?? 'Failed to create ministry',
        );
      }

      return MinistryModel.fromJson(responseData['data']);
    } on DioException catch (e) {
      throw ServerException(message: _handleDioError(e));
    } catch (e) {
      if (e is ServerException) rethrow;
      throw ServerException(message: e.toString());
    }
  }

  @override
  Future<Ministry> updateMinistry({
    required String id,
    String? name,
    String? description,
    String? email,
    String? phone,
    String? address,
    String? website,
    Uint8List? logoBytes,
    String? logoFileName,
  }) async {
    try {
      final formData = FormData.fromMap({
        if (name != null) 'name': name,
        if (description != null) 'description': description,
        if (email != null) 'email': email,
        if (phone != null) 'phone': phone,
        if (address != null) 'address': address,
        if (website != null) 'website': website,
        if (logoBytes != null && logoFileName != null)
          'logo': MultipartFile.fromBytes(logoBytes, filename: logoFileName),
      });

      final responseData = await apiClient.patch(
        ApiEndpoints.adminMinistryUpdate(id),
        data: formData,
        options: Options(contentType: 'multipart/form-data'),
      );

      if (responseData['success'] != true) {
        throw ServerException(
          message: responseData['error'] ?? 'Failed to update ministry',
        );
      }

      return MinistryModel.fromJson(responseData['data']);
    } on DioException catch (e) {
      throw ServerException(message: _handleDioError(e));
    } catch (e) {
      if (e is ServerException) rethrow;
      throw ServerException(message: e.toString());
    }
  }

  @override
  Future<void> deleteMinistry(String id) async {
    try {
      final responseData = await apiClient.delete(
        ApiEndpoints.adminMinistryDelete(id),
      );

      if (responseData['success'] != true) {
        throw ServerException(
          message: responseData['error'] ?? 'Failed to delete ministry',
        );
      }
    } on DioException catch (e) {
      throw ServerException(message: _handleDioError(e));
    } catch (e) {
      if (e is ServerException) rethrow;
      throw ServerException(message: e.toString());
    }
  }

  @override
  Future<Ministry> activateMinistry(String id) async {
    try {
      final responseData = await apiClient.post(
        ApiEndpoints.adminMinistryActivate(id),
      );

      if (responseData['success'] != true) {
        throw ServerException(
          message: responseData['error'] ?? 'Failed to activate ministry',
        );
      }

      // Handle case where backend doesn't return ministry data
      final data = responseData['data'];
      if (data == null) {
        // Fetch the updated ministry separately
        return await getMinistryById(id);
      }

      return MinistryModel.fromJson(data as Map<String, dynamic>);
    } on DioException catch (e) {
      throw ServerException(message: _handleDioError(e));
    } catch (e) {
      if (e is ServerException) rethrow;
      throw ServerException(message: e.toString());
    }
  }

  @override
  Future<Ministry> suspendMinistry(String id, {String? reason}) async {
    try {
      final responseData = await apiClient.post(
        ApiEndpoints.adminMinistrySuspend(id),
        data: reason != null ? {'reason': reason} : null,
      );

      if (responseData['success'] != true) {
        throw ServerException(
          message: responseData['error'] ?? 'Failed to suspend ministry',
        );
      }

      // Handle case where backend doesn't return ministry data
      final data = responseData['data'];
      if (data == null) {
        // Fetch the updated ministry separately
        return await getMinistryById(id);
      }

      return MinistryModel.fromJson(data as Map<String, dynamic>);
    } on DioException catch (e) {
      throw ServerException(message: _handleDioError(e));
    } catch (e) {
      if (e is ServerException) rethrow;
      throw ServerException(message: e.toString());
    }
  }

  @override
  Future<List<Ministry>> getDeletedMinistries() async {
    try {
      final responseData = await apiClient.get(
        ApiEndpoints.adminMinistriesDeleted,
      );

      if (responseData['success'] != true) {
        throw ServerException(
          message:
              responseData['error'] ?? 'Failed to fetch deleted ministries',
        );
      }

      final data = responseData['data'] as List<dynamic>? ?? [];
      return data
          .map((json) => MinistryModel.fromJson(json as Map<String, dynamic>))
          .toList();
    } on DioException catch (e) {
      throw ServerException(message: _handleDioError(e));
    } catch (e) {
      if (e is ServerException) rethrow;
      throw ServerException(message: e.toString());
    }
  }

  @override
  Future<Ministry> restoreMinistry(String id) async {
    try {
      final responseData = await apiClient.post(
        ApiEndpoints.adminMinistryRestore(id),
      );

      if (responseData['success'] != true) {
        throw ServerException(
          message: responseData['error'] ?? 'Failed to restore ministry',
        );
      }

      // Handle case where backend doesn't return ministry data
      final data = responseData['data'];
      if (data == null) {
        // Fetch the updated ministry separately
        return await getMinistryById(id);
      }

      return MinistryModel.fromJson(data as Map<String, dynamic>);
    } on DioException catch (e) {
      throw ServerException(message: _handleDioError(e));
    } catch (e) {
      if (e is ServerException) rethrow;
      throw ServerException(message: e.toString());
    }
  }

  @override
  Future<void> hardDeleteMinistry(String id) async {
    try {
      final responseData = await apiClient.post(
        ApiEndpoints.adminMinistryHardDelete(id),
        data: {'confirm': true},
      );

      if (responseData['success'] != true) {
        throw ServerException(
          message:
              responseData['error'] ?? 'Failed to permanently delete ministry',
        );
      }
    } on DioException catch (e) {
      throw ServerException(message: _handleDioError(e));
    } catch (e) {
      if (e is ServerException) rethrow;
      throw ServerException(message: e.toString());
    }
  }

  @override
  Future<void> resetMinistryPassword(String id, String newPassword) async {
    try {
      final responseData = await apiClient.post(
        ApiEndpoints.adminMinistryResetPassword(id),
        data: {'new_password': newPassword},
      );

      if (responseData['success'] != true) {
        throw ServerException(
          message: responseData['error'] ?? 'Failed to reset password',
        );
      }
    } on DioException catch (e) {
      throw ServerException(message: _handleDioError(e));
    } catch (e) {
      if (e is ServerException) rethrow;
      throw ServerException(message: e.toString());
    }
  }

  String _handleDioError(DioException e) {
    if (e.type == DioExceptionType.connectionTimeout) {
      return 'Connection timeout. Please check your internet connection.';
    } else if (e.type == DioExceptionType.receiveTimeout) {
      return 'Server is taking too long to respond. Please try again.';
    } else if (e.type == DioExceptionType.connectionError) {
      return 'Unable to connect to server. Please check your internet.';
    } else if (e.response != null) {
      final statusCode = e.response!.statusCode;
      final data = e.response!.data;

      if (data is Map && data.containsKey('error')) {
        return data['error'].toString();
      }

      switch (statusCode) {
        case 401:
          return 'Unauthorized. Please login again.';
        case 403:
          return 'You do not have permission to perform this action.';
        case 404:
          return 'Resource not found.';
        case 400:
          return 'Invalid request. Please check your inputs.';
        case 500:
          return 'Server error. Please try again later.';
        default:
          return 'Server error ($statusCode). Please try again.';
      }
    }
    return 'Network error. Please check your connection.';
  }

  // ============================================
  // MINISTRY SELF-MANAGEMENT IMPLEMENTATIONS
  // ============================================

  @override
  Future<Ministry> getMyMinistry() async {
    try {
      final responseData = await apiClient.get(ApiEndpoints.myMinistry);

      if (responseData['success'] != true) {
        throw ServerException(
          message: responseData['error'] ?? 'Failed to fetch ministry profile',
        );
      }

      return MinistryModel.fromJson(responseData['data']);
    } on DioException catch (e) {
      throw ServerException(message: _handleDioError(e));
    } catch (e) {
      if (e is ServerException) rethrow;
      throw ServerException(message: e.toString());
    }
  }

  @override
  Future<Ministry> updateMyMinistry({
    String? description,
    String? phone,
    String? address,
    String? website,
    Uint8List? logoBytes,
    String? logoFileName,
  }) async {
    try {
      final formData = FormData.fromMap({
        if (description != null) 'description': description,
        if (phone != null) 'phone': phone,
        if (address != null) 'address': address,
        if (website != null) 'website': website,
        if (logoBytes != null && logoFileName != null)
          'logo': MultipartFile.fromBytes(logoBytes, filename: logoFileName),
      });

      final responseData = await apiClient.patch(
        ApiEndpoints.myMinistry,
        data: formData,
        options: Options(contentType: 'multipart/form-data'),
      );

      if (responseData['success'] != true) {
        throw ServerException(
          message: responseData['error'] ?? 'Failed to update ministry profile',
        );
      }

      return MinistryModel.fromJson(responseData['data']);
    } on DioException catch (e) {
      throw ServerException(message: _handleDioError(e));
    } catch (e) {
      if (e is ServerException) rethrow;
      throw ServerException(message: e.toString());
    }
  }
}
