# Generated by Django 6.0.1 on 2026-01-09 19:15

import core.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ministry/Department name', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Ministry description')),
                ('email', models.EmailField(help_text='Official contact email', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, help_text='Ministry logo (uploaded to Cloudinary /logos folder)', null=True, storage=core.storage.LogoCloudinaryStorage(), upload_to=core.storage.LogoCloudinaryStorage.get_upload_path)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('pending', 'Pending Approval')], default='pending', max_length=20)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Ministry-specific configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft deleted - data remains but ministry is inaccessible')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When the ministry was soft deleted', null=True)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Super admin who deleted the ministry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_ministries', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(blank=True, help_text='Place/Location this ministry belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ministries', to='places.place')),
            ],
            options={
                'verbose_name': 'Ministry',
                'verbose_name_plural': 'Ministries',
                'ordering': ['place', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MinistryInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email to invite', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='ministry.ministry')),
            ],
            options={
                'verbose_name': 'Ministry Invitation',
                'verbose_name_plural': 'Ministry Invitations',
            },
        ),
        migrations.CreateModel(
            name='MinistryMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ministry.ministry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ministry_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ministry Admin',
                'verbose_name_plural': 'Ministry Admins',
            },
        ),
        migrations.AddIndex(
            model_name='ministry',
            index=models.Index(fields=['place', 'slug'], name='ministry_mi_place_i_8994a3_idx'),
        ),
        migrations.AddIndex(
            model_name='ministry',
            index=models.Index(fields=['place', 'status'], name='ministry_mi_place_i_cb3347_idx'),
        ),
        migrations.AddIndex(
            model_name='ministry',
            index=models.Index(fields=['status'], name='ministry_mi_status_c06515_idx'),
        ),
        migrations.AddIndex(
            model_name='ministry',
            index=models.Index(fields=['created_at'], name='ministry_mi_created_550a82_idx'),
        ),
        migrations.AddIndex(
            model_name='ministry',
            index=models.Index(fields=['is_deleted'], name='ministry_mi_is_dele_e2a2e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ministry',
            unique_together={('place', 'slug')},
        ),
        migrations.AddIndex(
            model_name='ministryinvitation',
            index=models.Index(fields=['ministry', 'status'], name='ministry_mi_ministr_e0695d_idx'),
        ),
        migrations.AddIndex(
            model_name='ministryinvitation',
            index=models.Index(fields=['email'], name='ministry_mi_email_929de3_idx'),
        ),
        migrations.AddIndex(
            model_name='ministryinvitation',
            index=models.Index(fields=['token'], name='ministry_mi_token_930bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='ministrymember',
            index=models.Index(fields=['ministry'], name='ministry_mi_ministr_d4dde8_idx'),
        ),
        migrations.AddIndex(
            model_name='ministrymember',
            index=models.Index(fields=['user', 'is_active'], name='ministry_mi_user_id_fc5e6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ministrymember',
            unique_together={('ministry', 'user')},
        ),
    ]
