# Generated by Django 6.0.1 on 2026-01-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name)', max_length=100),
        ),
    ]
