# Generated by Django 6.0.1 on 2026-01-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0002_alter_ministry_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='password',
            field=models.CharField(blank=True, help_text='Hashed password for ministry login', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='email',
            field=models.EmailField(help_text='Official contact email (used for login)', max_length=254, unique=True),
        ),
    ]
