# Generated by Django 6.0.1 on 2026-01-11 08:29

import core.storage
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0003_ministry_password_alter_ministry_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Staff service name', max_length=255)),
                ('email', models.EmailField(help_text='Staff login email', max_length=254, unique=True)),
                ('password', models.CharField(help_text='Hashed password for staff login', max_length=128)),
                ('logo', models.ImageField(blank=True, help_text='Staff service logo (uploaded to Cloudinary /logos folder)', null=True, storage=core.storage.LogoCloudinaryStorage(), upload_to=core.storage.LogoCloudinaryStorage.get_upload_path)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ministry', models.ForeignKey(help_text='Ministry this staff service belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='ministry.ministry')),
            ],
            options={
                'verbose_name': 'Staff Service',
                'verbose_name_plural': 'Staff Services',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ministry', 'status'], name='ministry_st_ministr_43cad6_idx'), models.Index(fields=['email'], name='ministry_st_email_45c6ca_idx'), models.Index(fields=['status'], name='ministry_st_status_919270_idx')],
            },
        ),
    ]
