# Generated by Django 6.0.1 on 2026-01-12 21:16

import core.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Staff full name', max_length=100)),
                ('contact', models.CharField(help_text='Contact number', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Staff profile photo (uploaded to Cloudinary /avatars folder)', null=True, storage=core.storage.AvatarCloudinaryStorage(), upload_to=core.storage.AvatarCloudinaryStorage.get_upload_path)),
                ('is_active', models.BooleanField(default=True, help_text='Whether staff can login and access the service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_staff', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(help_text='Service this staff is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='services.service')),
                ('user', models.OneToOneField(help_text='User account for this staff member', on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['service'], name='staff_staff_service_f432c8_idx'), models.Index(fields=['user'], name='staff_staff_user_id_32b4ab_idx'), models.Index(fields=['is_active'], name='staff_staff_is_acti_0db61a_idx'), models.Index(fields=['is_deleted'], name='staff_staff_is_dele_2a1a0d_idx')],
            },
        ),
    ]
