import 'dart:typed_data';

import 'package:dartz/dartz.dart';
import 'package:sewa_web/core/errors/failures.dart';
import 'package:sewa_web/features/auth/domain/entities/ministry.dart';
import 'package:sewa_web/features/super_admin/domain/entities/place_filter_option.dart';

/// Repository interface for Ministry operations
/// Following Clean Architecture pattern
abstract class MinistryRepository {
  /// Get all places for filter dropdown
  /// API: GET /ministry/admin/places/
  /// Returns list of places with ministry counts
  Future<Either<Failure, List<PlaceFilterOption>>> getPlacesForFilter();

  /// Get all ministries for Super Admin (requires auth)
  /// Now supports optional placeId filter
  /// API: GET /ministry/admin/?place=<uuid>
  Future<Either<Failure, List<Ministry>>> getAdminMinistries({
    String? place,
    String? status,
    String? search,
    int? page,
    int? pageSize,
  });

  /// Get ministry details by ID
  Future<Either<Failure, Ministry>> getMinistryById(String id);

  /// Create a new ministry
  /// placeId is required - ministry MUST belong to a place
  /// email and password are required for ministry admin login credentials
  /// Note: slug is auto-generated by backend from ministry name
  Future<Either<Failure, Ministry>> createMinistry({
    required String placeId,
    required String name,
    required String email,
    required String password,
    String? description,
    String? phone,
    String? address,
    String? website,
    Uint8List? logoBytes,
    String? logoFileName,
  });

  /// Update ministry
  Future<Either<Failure, Ministry>> updateMinistry({
    required String id,
    String? name,
    String? description,
    String? email,
    String? phone,
    String? address,
    String? website,
    Uint8List? logoBytes,
    String? logoFileName,
  });

  /// Delete ministry
  Future<Either<Failure, void>> deleteMinistry(String id);

  /// Activate ministry
  Future<Either<Failure, Ministry>> activateMinistry(String id);

  /// Suspend ministry
  Future<Either<Failure, Ministry>> suspendMinistry(
    String id, {
    String? reason,
  });

  /// Get list of deleted ministries (soft-deleted)
  Future<Either<Failure, List<Ministry>>> getDeletedMinistries();

  /// Restore a soft-deleted ministry
  Future<Either<Failure, Ministry>> restoreMinistry(String id);

  /// Hard delete ministry (permanent, cannot be undone)
  Future<Either<Failure, void>> hardDeleteMinistry(String id);

  /// Reset ministry admin password
  Future<Either<Failure, void>> resetMinistryPassword(
    String id,
    String newPassword,
  );

  // ============================================
  // MINISTRY SELF-MANAGEMENT (Staff users)
  // ============================================

  /// Get own ministry details (for ministry staff)
  Future<Either<Failure, Ministry>> getMyMinistry();

  /// Update own ministry profile (for ministry staff)
  /// Note: Limited fields can be updated by ministry staff
  Future<Either<Failure, Ministry>> updateMyMinistry({
    String? description,
    String? phone,
    String? address,
    String? website,
    Uint8List? logoBytes,
    String? logoFileName,
  });
}
