# Generated by Django 6.0.1 on 2026-01-07 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantinvitation',
            options={'verbose_name': 'Ministry Invitation', 'verbose_name_plural': 'Ministry Invitations'},
        ),
        migrations.AlterModelOptions(
            name='tenantmember',
            options={'verbose_name': 'Ministry Staff', 'verbose_name_plural': 'Ministry Staff'},
        ),
        migrations.RemoveIndex(
            model_name='tenantmember',
            name='tenants_ten_tenant__984cd1_idx',
        ),
        migrations.RemoveField(
            model_name='tenantinvitation',
            name='role',
        ),
        migrations.AddIndex(
            model_name='tenantmember',
            index=models.Index(fields=['tenant'], name='tenants_ten_tenant__0dacb8_idx'),
        ),
        migrations.RemoveField(
            model_name='tenantmember',
            name='role',
        ),
    ]
