# Generated by Django 6.0.1 on 2026-01-09 19:15

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ministry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Category name', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('icon', models.CharField(blank=True, help_text='Icon class/name', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_service_categories', to=settings.AUTH_USER_MODEL)),
                ('ministry', models.ForeignKey(help_text='Ministry that owns this category', on_delete=django.db.models.deletion.CASCADE, related_name='service_categories', to='ministry.ministry')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Service name', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=200)),
                ('short_description', models.CharField(blank=True, help_text='Brief description', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Full service description')),
                ('service_type', models.CharField(choices=[('online', 'Online Service'), ('offline', 'Offline Service'), ('hybrid', 'Hybrid (Online + Offline)')], default='online', max_length=20)),
                ('processing_time', models.CharField(choices=[('instant', 'Instant'), ('same_day', 'Same Day'), ('1_3_days', '1-3 Days'), ('1_week', '1 Week'), ('2_weeks', '2 Weeks'), ('1_month', '1 Month'), ('variable', 'Variable')], default='variable', max_length=20)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Service fee in NPR', max_digits=10)),
                ('fee_description', models.CharField(blank=True, help_text='Fee details', max_length=200)),
                ('required_documents', models.JSONField(blank=True, default=list, help_text='List of required documents')),
                ('eligibility_criteria', models.TextField(blank=True, help_text='Who can apply')),
                ('form_schema', models.JSONField(blank=True, default=dict, help_text='JSON Schema for the application form')),
                ('external_url', models.URLField(blank=True, help_text='External service portal URL')),
                ('icon', models.CharField(blank=True, help_text='Icon class/name', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on ministry homepage')),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False, help_text='Visible to citizens')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_services', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_services', to=settings.AUTH_USER_MODEL)),
                ('ministry', models.ForeignKey(help_text='Ministry that provides this service', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='ministry.ministry')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_services', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Service category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicecategory')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this staff assignment is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(help_text='Service this staff is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='services.service')),
                ('user', models.ForeignKey(help_text='User assigned as staff', on_delete=django.db.models.deletion.CASCADE, related_name='service_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Staff',
                'verbose_name_plural': 'Service Staff',
            },
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['ministry', 'is_active'], name='services_se_ministr_c7c33c_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['slug'], name='services_se_slug_89aee3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicecategory',
            unique_together={('ministry', 'slug')},
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['ministry', 'is_active', 'is_published'], name='services_se_ministr_b9ea08_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_active'], name='services_se_categor_b50c86_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['service_type'], name='services_se_service_9fa833_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['slug'], name='services_se_slug_4657d0_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_featured'], name='services_se_is_feat_35b40d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('ministry', 'slug')},
        ),
        migrations.AddIndex(
            model_name='servicestaff',
            index=models.Index(fields=['service', 'is_active'], name='services_se_service_215138_idx'),
        ),
        migrations.AddIndex(
            model_name='servicestaff',
            index=models.Index(fields=['user', 'is_active'], name='services_se_user_id_7e24d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicestaff',
            unique_together={('service', 'user')},
        ),
    ]
