# Generated by Django 6.0.1 on 2026-01-28 04:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='queued', max_length=20)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('fastapi_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_logs', to='notices.notice')),
            ],
            options={
                'db_table': 'rag_bridge_ingestion_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['notice', 'status'], name='rag_bridge__notice__402cec_idx'), models.Index(fields=['status', 'created_at'], name='rag_bridge__status_c1c11c_idx')],
            },
        ),
    ]
