# Generated by Django 6.0.1 on 2026-01-28 04:06

import django.db.models.deletion
import notices.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ministry', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('file', models.FileField(help_text='PDF or image file (max 10MB)', upload_to='notices/', validators=[notices.models.validate_file_extension, notices.models.validate_file_size])),
                ('file_type', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('ingestion_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('ingestion_error', models.TextField(blank=True)),
                ('ingested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_notices', to=settings.AUTH_USER_MODEL)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='ministry.ministry')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='services.service')),
            ],
            options={
                'db_table': 'notices_notice',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ministry', 'is_active'], name='notices_not_ministr_4d64f0_idx'), models.Index(fields=['service', 'is_active'], name='notices_not_service_b58ac4_idx'), models.Index(fields=['created_at'], name='notices_not_created_8ebc7b_idx'), models.Index(fields=['ingestion_status'], name='notices_not_ingesti_30df00_idx'), models.Index(fields=['-created_at', 'is_active'], name='notices_not_created_b40203_idx')],
            },
        ),
    ]
