# Generated by Django 6.0.1 on 2026-01-12 21:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ministry', '0001_initial'),
        ('officials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('office_start_time', models.TimeField(help_text='Office opening time (e.g., 10:00)')),
                ('office_end_time', models.TimeField(help_text='Office closing time (e.g., 17:00)')),
                ('lunch_start_time', models.TimeField(blank=True, help_text='Lunch break start time (e.g., 13:00)', null=True)),
                ('lunch_end_time', models.TimeField(blank=True, help_text='Lunch break end time (e.g., 14:00)', null=True)),
                ('average_service_time_minutes', models.IntegerField(default=15, help_text='Average time to serve one token (in minutes)')),
                ('daily_capacity', models.IntegerField(default=50, help_text='Maximum tokens per day')),
                ('documents_required', models.JSONField(blank=True, default=list, help_text='List of required documents (JSON array)')),
                ('enable_progress_tracking', models.BooleanField(default=False, help_text='Enable progress tracking for tokens (requires ServiceProgressStep configuration)')),
                ('active', models.BooleanField(default=True, help_text='Whether queue is active for this service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_service', models.OneToOneField(help_text='Staff service for which queue is configured', on_delete=django.db.models.deletion.CASCADE, related_name='queue_config', to='ministry.staffservice')),
            ],
            options={
                'verbose_name': 'Queue Configuration',
                'verbose_name_plural': 'Queue Configurations',
            },
        ),
        migrations.CreateModel(
            name='DailyQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date for which this queue is created')),
                ('next_token_number', models.IntegerField(default=1, help_text='Next token number to assign')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queue_config', models.ForeignKey(help_text='Queue configuration for this daily queue', on_delete=django.db.models.deletion.CASCADE, related_name='daily_queues', to='queue_management.queueconfiguration')),
            ],
            options={
                'verbose_name': 'Daily Queue',
                'verbose_name_plural': 'Daily Queues',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='QueueToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_number', models.IntegerField(help_text='Token number for the day')),
                ('expected_service_time', models.DateTimeField(help_text='Expected time when citizen will be served (UTC)')),
                ('no_show_count', models.IntegerField(default=0, help_text='Number of times citizen was marked as no-show (max 2)')),
                ('active', models.BooleanField(default=True, help_text='False means token is finished (served/cancelled)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(help_text='Citizen who booked this token', on_delete=django.db.models.deletion.CASCADE, related_name='queue_tokens', to=settings.AUTH_USER_MODEL)),
                ('daily_queue', models.ForeignKey(help_text='Daily queue for this token', on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='queue_management.dailyqueue')),
            ],
            options={
                'verbose_name': 'Queue Token',
                'verbose_name_plural': 'Queue Tokens',
                'ordering': ['token_number'],
            },
        ),
        migrations.CreateModel(
            name='QueueEventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('CREATED', 'Token Created'), ('SERVED', 'Token Served'), ('NO_SHOW_PUSHED', 'No Show - Pushed Back'), ('CANCELLED', 'Token Cancelled'), ('PROGRESS_COMPLETED', 'Progress Step Completed')], help_text='Event type', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, help_text='User who performed this action (null for system)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_events', to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(help_text='Token for which this event occurred', on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='queue_management.queuetoken')),
            ],
            options={
                'verbose_name': 'Queue Event Log',
                'verbose_name_plural': 'Queue Event Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProgressStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_order', models.IntegerField(help_text='Order of the step (1, 2, 3, ...)')),
                ('title', models.CharField(help_text="Title of the step (e.g., 'Sent to admin', 'Seen by Chairperson')", max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of what happens in this step')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('official', models.ForeignKey(help_text='Official responsible for this step', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_steps', to='officials.ministryofficial')),
                ('queue_config', models.ForeignKey(help_text='Queue configuration for which this step is defined', on_delete=django.db.models.deletion.CASCADE, related_name='progress_steps', to='queue_management.queueconfiguration')),
            ],
            options={
                'verbose_name': 'Service Progress Step',
                'verbose_name_plural': 'Service Progress Steps',
                'ordering': ['queue_config', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='TokenProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False, help_text='Whether this step has been completed')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When this step was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(help_text='Progress step being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='token_progress', to='queue_management.serviceprogressstep')),
                ('token', models.ForeignKey(help_text='Token for which progress is tracked', on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='queue_management.queuetoken')),
            ],
            options={
                'verbose_name': 'Token Progress',
                'verbose_name_plural': 'Token Progress Records',
                'ordering': ['token', 'step__step_order'],
            },
        ),
        migrations.AddIndex(
            model_name='queueconfiguration',
            index=models.Index(fields=['staff_service', 'active'], name='queue_manag_staff_s_c8f7ed_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyqueue',
            index=models.Index(fields=['queue_config', 'date'], name='queue_manag_queue_c_493928_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyqueue',
            index=models.Index(fields=['date'], name='queue_manag_date_25aac0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyqueue',
            unique_together={('queue_config', 'date')},
        ),
        migrations.AddIndex(
            model_name='queuetoken',
            index=models.Index(fields=['daily_queue', 'active'], name='queue_manag_daily_q_1ac03d_idx'),
        ),
        migrations.AddIndex(
            model_name='queuetoken',
            index=models.Index(fields=['citizen', 'active'], name='queue_manag_citizen_0ad993_idx'),
        ),
        migrations.AddIndex(
            model_name='queuetoken',
            index=models.Index(fields=['expected_service_time'], name='queue_manag_expecte_b7a4c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='queuetoken',
            unique_together={('daily_queue', 'token_number')},
        ),
        migrations.AddIndex(
            model_name='queueeventlog',
            index=models.Index(fields=['token', 'event'], name='queue_manag_token_i_3fcd4e_idx'),
        ),
        migrations.AddIndex(
            model_name='queueeventlog',
            index=models.Index(fields=['created_at'], name='queue_manag_created_bd9663_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprogressstep',
            index=models.Index(fields=['queue_config', 'step_order'], name='queue_manag_queue_c_d7ba6f_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprogressstep',
            index=models.Index(fields=['official'], name='queue_manag_officia_6d9eb7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceprogressstep',
            unique_together={('queue_config', 'step_order')},
        ),
        migrations.AddIndex(
            model_name='tokenprogress',
            index=models.Index(fields=['token', 'completed'], name='queue_manag_token_i_f83b54_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenprogress',
            index=models.Index(fields=['step', 'completed'], name='queue_manag_step_id_42db20_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tokenprogress',
            unique_together={('token', 'step')},
        ),
    ]
