# Generated by Django 6.0.1 on 2026-01-25 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0001_initial'),
        ('officials', '0001_initial'),
        ('queue_management', '0004_remove_description_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tokenprogress',
            new_name='queue_manag_complet_e3fe4a_idx',
            old_name='queue_manag_completed_by_idx',
        ),
        migrations.AddField(
            model_name='queueconfiguration',
            name='emergency_allowed',
            field=models.BooleanField(default=False, help_text='Allow emergency token bookings'),
        ),
        migrations.AddField(
            model_name='queueconfiguration',
            name='emergency_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Additional fee for emergency bookings (in local currency)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='queueconfiguration',
            name='emergency_quota_per_day',
            field=models.IntegerField(blank=True, default=5, help_text='Maximum emergency tokens allowed per day (included in total capacity)', null=True),
        ),
        migrations.AddField(
            model_name='queueconfiguration',
            name='enable_progress_tracking',
            field=models.BooleanField(default=False, help_text='Enable multi-step progress tracking for tokens'),
        ),
        migrations.AddField(
            model_name='queueconfiguration',
            name='higher_official',
            field=models.ForeignKey(blank=True, help_text='Higher official assigned to this service (if absent, service closes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_queues', to='officials.ministryofficial'),
        ),
        migrations.AddField(
            model_name='queueconfiguration',
            name='ministry',
            field=models.ForeignKey(blank=True, help_text='Ministry owning this queue configuration (auto-set from staff_service)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue_configs', to='ministry.ministry'),
        ),
        migrations.AddField(
            model_name='queueconfiguration',
            name='prebooking_allowed',
            field=models.BooleanField(default=False, help_text='Allow citizens to pre-book tokens in advance'),
        ),
        migrations.AddField(
            model_name='queueconfiguration',
            name='prebooking_lead_hours',
            field=models.IntegerField(blank=True, default=24, help_text='Minimum hours in advance for prebooking (e.g., 24 hours)', null=True),
        ),
        migrations.AddField(
            model_name='queueconfiguration',
            name='prebooking_quota_per_day',
            field=models.IntegerField(blank=True, default=10, help_text='Maximum prebooked tokens allowed per day (included in total capacity)', null=True),
        ),
        migrations.AddField(
            model_name='queuetoken',
            name='booking_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('PREBOOKED', 'Pre-booked'), ('EMERGENCY', 'Emergency')], default='REGULAR', help_text='Type of booking (REGULAR, PREBOOKED, EMERGENCY)', max_length=10),
        ),
        migrations.AddField(
            model_name='queuetoken',
            name='emergency_fee_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fee paid for emergency booking (0 for regular/prebooked)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='queueconfiguration',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether queue is active for this service (false = completely closed)'),
        ),
        migrations.AlterField(
            model_name='queueconfiguration',
            name='average_service_time_minutes',
            field=models.IntegerField(default=15, help_text='Average time to serve one token (in minutes) - used for dynamic capacity calculation'),
        ),
        migrations.AlterField(
            model_name='queueconfiguration',
            name='documents_required',
            field=models.JSONField(blank=True, default=list, help_text='List of required documents: [{"name": "Citizenship", "sample_image_url": "..."}]'),
        ),
        migrations.AlterField(
            model_name='queueconfiguration',
            name='staff_service',
            field=models.OneToOneField(help_text='Staff service for which queue is configured (one staff per service)', on_delete=django.db.models.deletion.CASCADE, related_name='queue_config', to='ministry.staffservice'),
        ),
        migrations.AddIndex(
            model_name='queueconfiguration',
            index=models.Index(fields=['ministry', 'active'], name='queue_manag_ministr_20e681_idx'),
        ),
        migrations.AddIndex(
            model_name='queueconfiguration',
            index=models.Index(fields=['higher_official'], name='queue_manag_higher__580af0_idx'),
        ),
        migrations.AddIndex(
            model_name='queuetoken',
            index=models.Index(fields=['booking_type'], name='queue_manag_booking_2f94b5_idx'),
        ),
    ]
