# Generated by Django 6.0.1 on 2026-01-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_management', '0005_queue_config_refactoring'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='serviceprogressstep',
            name='queue_manag_officia_6d9eb7_idx',
        ),
        migrations.AlterField(
            model_name='serviceprogressstep',
            name='title',
            field=models.CharField(help_text="Title of the step (e.g., 'Seen by Staff', 'Seen by Chairman')", max_length=200),
        ),
        migrations.RemoveField(
            model_name='serviceprogressstep',
            name='official',
        ),
    ]
