# Generated by Django 6.0.1 on 2026-01-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0001_initial'),
        ('queue_management', '0006_remove_official_from_progress_steps'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='queueconfiguration',
            name='queue_manag_higher__580af0_idx',
        ),
        migrations.AddField(
            model_name='queueconfiguration',
            name='higher_officials',
            field=models.ManyToManyField(blank=True, help_text='Higher officials assigned to this service (if all absent, service closes)', related_name='assigned_queues', to='officials.ministryofficial'),
        ),
        migrations.RemoveField(
            model_name='queueconfiguration',
            name='daily_capacity',
        ),
        migrations.RemoveField(
            model_name='queueconfiguration',
            name='higher_official',
        ),
    ]
