# Generated by Django 6.0.1 on 2026-01-27 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_management', '0007_multiple_officials_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Skip progress_tracking_enabled - already exists in database
        migrations.AddField(
            model_name='queuetoken',
            name='pending_priority_date',
            field=models.DateField(blank=True, help_text='Date when this pending token gets priority service', null=True),
        ),
        migrations.AddField(
            model_name='queuetoken',
            name='pending_reason',
            field=models.TextField(blank=True, help_text='Reason for moving to pending (government fault only)', null=True),
        ),
        migrations.AddField(
            model_name='queuetoken',
            name='service_started_at',
            field=models.DateTimeField(blank=True, help_text='When the token service countdown started', null=True),
        ),
        migrations.AddField(
            model_name='queuetoken',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting in Queue'), ('IN_SERVICE', 'Currently Being Served'), ('PENDING', 'Pending (Government Fault)'), ('COMPLETED', 'Service Completed'), ('CANCELLED', 'Cancelled')], default='WAITING', help_text='Current token status', max_length=15),
        ),
        migrations.AlterField(
            model_name='queueeventlog',
            name='event',
            field=models.CharField(choices=[('CREATED', 'Token Created'), ('IN_SERVICE', 'Service Started (Countdown)'), ('COMPLETED', 'Service Completed'), ('NO_SHOW', 'Citizen No Show'), ('PUSHED_BACK', 'Pushed Back in Queue'), ('MOVED_TO_PENDING', 'Moved to Pending Queue'), ('CANCELLED', 'Token Cancelled'), ('PROGRESS_COMPLETED', 'Progress Step Completed'), ('PENDING_EMAIL_SENT', 'Pending Email Sent'), ('PRIORITY_RESTORED', 'Priority Service Restored'), ('SERVED', 'Token Served (Legacy)'), ('NO_SHOW_PUSHED', 'No Show - Pushed Back (Legacy)')], help_text='Event type', max_length=20),
        ),
        migrations.AlterField(
            model_name='queuetoken',
            name='active',
            field=models.BooleanField(default=True, help_text='False means token is finished (served/cancelled) - DEPRECATED, use status'),
        ),
        migrations.AddIndex(
            model_name='queuetoken',
            index=models.Index(fields=['daily_queue', 'status'], name='queue_manag_daily_q_5f3d71_idx'),
        ),
        migrations.AddIndex(
            model_name='queuetoken',
            index=models.Index(fields=['status'], name='queue_manag_status_9adccc_idx'),
        ),
        migrations.AddIndex(
            model_name='queuetoken',
            index=models.Index(fields=['pending_priority_date'], name='queue_manag_pending_f60916_idx'),
        ),
    ]
