# Generated by Django 6.0.1 on 2026-01-27 20:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text="Citizen's full name", max_length=100)),
                ('is_profile_complete', models.BooleanField(default=False, help_text='Whether profile setup is completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(help_text='Selected place for service access', on_delete=django.db.models.deletion.PROTECT, related_name='citizens', to='places.place')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'citizen'}, on_delete=django.db.models.deletion.CASCADE, related_name='citizen_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Citizen Profile',
                'verbose_name_plural': 'Citizen Profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='mobile_init_user_id_db8dae_idx'), models.Index(fields=['place'], name='mobile_init_place_i_734f99_idx'), models.Index(fields=['is_profile_complete'], name='mobile_init_is_prof_78d009_idx')],
            },
        ),
    ]
