# Generated by Django 6.0.1 on 2026-01-12 21:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ministry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryOfficial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name of the official', max_length=255)),
                ('role', models.CharField(help_text='Role/designation (e.g., Chairperson, Secretary, President)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this official is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ministry', models.ForeignKey(help_text='Ministry this official belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='officials', to='ministry.ministry')),
            ],
            options={
                'verbose_name': 'Ministry Official',
                'verbose_name_plural': 'Ministry Officials',
                'ordering': ['ministry', 'name'],
                'indexes': [models.Index(fields=['ministry', 'is_active'], name='officials_m_ministr_951054_idx'), models.Index(fields=['is_active'], name='officials_m_is_acti_cd3643_idx')],
                'unique_together': {('ministry', 'name', 'role')},
            },
        ),
    ]
