# Generated by Django 6.0.1 on 2026-01-12 21:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date for which attendance is being marked')),
                ('person_type', models.CharField(choices=[('STAFF', 'Staff'), ('OFFICIAL', 'Official')], help_text='Whether this record is for staff or official', max_length=10)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], default='PRESENT', help_text='Attendance status', max_length=10)),
                ('reason', models.TextField(blank=True, default='', help_text='Optional reason for absence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date'],
            },
        ),
    ]
