# Generated by Django 6.0.1 on 2026-01-12 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('ministry', '0001_initial'),
        ('officials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='marked_by',
            field=models.ForeignKey(help_text='Ministry admin who marked this attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='official',
            field=models.ForeignKey(blank=True, help_text='Official (if person_type=OFFICIAL)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='officials.ministryofficial'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='staff',
            field=models.ForeignKey(blank=True, help_text='Staff member (if person_type=STAFF)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='ministry.staffservice'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date', 'person_type'], name='attendance__date_bf5d70_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['staff', 'date'], name='attendance__staff_i_e54e15_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['official', 'date'], name='attendance__officia_3d2fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date', 'status'], name='attendance__date_64c311_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('person_type', 'STAFF')), fields=('staff', 'date'), name='unique_staff_date'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('person_type', 'OFFICIAL')), fields=('official', 'date'), name='unique_official_date'),
        ),
    ]
