import 'dart:typed_data';

import 'package:dartz/dartz.dart';
import 'package:sewa_web/core/errors/exceptions.dart';
import 'package:sewa_web/core/errors/failures.dart';
import 'package:sewa_web/core/network/network_info.dart';
import 'package:sewa_web/features/auth/domain/entities/ministry.dart';
import 'package:sewa_web/features/super_admin/data/data_sources/ministry_remote_data_source.dart';
import 'package:sewa_web/features/super_admin/domain/entities/place_filter_option.dart';
import 'package:sewa_web/features/super_admin/domain/repositories/ministry_repository.dart';

/// Implementation of MinistryRepository
/// Handles data fetching with proper error handling
class MinistryRepositoryImpl implements MinistryRepository {
  final MinistryRemoteDataSource remoteDataSource;
  final NetworkInfo networkInfo;

  MinistryRepositoryImpl({
    required this.remoteDataSource,
    required this.networkInfo,
  });

  @override
  Future<Either<Failure, List<PlaceFilterOption>>> getPlacesForFilter() async {
    if (!await networkInfo.isConnected) {
      return const Left(
        NetworkFailure(
          message: 'No internet connection. Please check your network.',
        ),
      );
    }

    try {
      final places = await remoteDataSource.getPlacesForFilter();
      return Right(places);
    } on ServerException catch (e) {
      return Left(ServerFailure(message: e.message));
    } catch (e) {
      return const Left(
        ServerFailure(
          message: 'An unexpected error occurred. Please try again.',
        ),
      );
    }
  }

  @override
  Future<Either<Failure, List<Ministry>>> getAdminMinistries({
    String? place,
    String? status,
    String? search,
    int? page,
    int? pageSize,
  }) async {
    if (!await networkInfo.isConnected) {
      return const Left(
        NetworkFailure(
          message: 'No internet connection. Please check your network.',
        ),
      );
    }

    try {
      final ministries = await remoteDataSource.getAdminMinistries(
        place: place,
        status: status,
        search: search,
        page: page,
        pageSize: pageSize,
      );
      return Right(ministries);
    } on ServerException catch (e) {
      return Left(ServerFailure(message: e.message));
    } catch (e) {
      return const Left(
        ServerFailure(
          message: 'An unexpected error occurred. Please try again.',
        ),
      );
    }
  }

  @override
  Future<Either<Failure, Ministry>> getMinistryById(String id) async {
    if (!await networkInfo.isConnected) {
      return const Left(
        NetworkFailure(
          message: 'No internet connection. Please check your network.',
        ),
      );
    }

    try {
      final ministry = await remoteDataSource.getMinistryById(id);
      return Right(ministry);
    } on ServerException catch (e) {
      return Left(ServerFailure(message: e.message));
    } catch (e) {
      return const Left(
        ServerFailure(
          message: 'An unexpected error occurred. Please try again.',
        ),
      );
    }
  }

  @override
  Future<Either<Failure, Ministry>> createMinistry({
    required String placeId,
    required String name,
    required String email,
    required String password,
    String? description,
    String? phone,
    String? address,
    String? website,
    Uint8List? logoBytes,
    String? logoFileName,
  }) async {
    if (!await networkInfo.isConnected) {
      return const Left(
        NetworkFailure(
          message: 'No internet connection. Please check your network.',
        ),
      );
    }

    try {
      // Note: slug is auto-generated by backend from ministry name
      final ministry = await remoteDataSource.createMinistry(
        placeId: placeId,
        name: name,
        email: email,
        password: password,
        description: description,
        phone: phone,
        address: address,
        website: website,
        logoBytes: logoBytes,
        logoFileName: logoFileName,
      );
      return Right(ministry);
    } on ServerException catch (e) {
      return Left(ServerFailure(message: e.message));
    } catch (e) {
      return const Left(
        ServerFailure(
          message: 'An unexpected error occurred. Please try again.',
        ),
      );
    }
  }

  @override
  Future<Either<Failure, Ministry>> updateMinistry({
    required String id,
    String? name,
    String? description,
    String? email,
    String? phone,
    String? address,
    String? website,
    Uint8List? logoBytes,
    String? logoFileName,
  }) async {
    if (!await networkInfo.isConnected) {
      return const Left(
        NetworkFailure(
          message: 'No internet connection. Please check your network.',
        ),
      );
    }

    try {
      final ministry = await remoteDataSource.updateMinistry(
        id: id,
        name: name,
        description: description,
        email: email,
        phone: phone,
        address: address,
        website: website,
        logoBytes: logoBytes,
        logoFileName: logoFileName,
      );
      return Right(ministry);
    } on ServerException catch (e) {
      return Left(ServerFailure(message: e.message));
    } catch (e) {
      return const Left(
        ServerFailure(
          message: 'An unexpected error occurred. Please try again.',
        ),
      );
    }
  }

  @override
  Future<Either<Failure, void>> deleteMinistry(String id) async {
    if (!await networkInfo.isConnected) {
      return const Left(
        NetworkFailure(
          message: 'No internet connection. Please check your network.',
        ),
      );
    }

    try {
      await remoteDataSource.deleteMinistry(id);
      return const Right(null);
    } on ServerException catch (e) {
      return Left(ServerFailure(message: e.message));
    } catch (e) {
      return const Left(
        ServerFailure(
          message: 'An unexpected error occurred. Please try again.',
        ),
      );
    }
  }

  @override
  Future<Either<Failure, Ministry>> activateMinistry(String id) async {
    if (!await networkInfo.isConnected) {
      return const Left(
        NetworkFailure(
          message: 'No internet connection. Please check your network.',
        ),
      );
    }

    try {
      final ministry = await remoteDataSource.activateMinistry(id);
      return Right(ministry);
    } on ServerException catch (e) {
      return Left(ServerFailure(message: e.message));
    } catch (e) {
      return const Left(
        ServerFailure(
          message: 'An unexpected error occurred. Please try again.',
        ),
      );
    }
  }

  @override
  Future<Either<Failure, Ministry>> suspendMinistry(
    String id, {
    String? reason,
  }) async {
    if (!await networkInfo.isConnected) {
      return const Left(
        NetworkFailure(
          message: 'No internet connection. Please check your network.',
        ),
      );
    }

    try {
      final ministry = await remoteDataSource.suspendMinistry(
        id,
        reason: reason,
      );
      return Right(ministry);
    } on ServerException catch (e) {
      return Left(ServerFailure(message: e.message));
    } catch (e) {
      return const Left(
        ServerFailure(
          message: 'An unexpected error occurred. Please try again.',
        ),
      );
    }
  }

  // ============================================
  // MINISTRY SELF-MANAGEMENT IMPLEMENTATIONS
  // ============================================

  @override
  Future<Either<Failure, List<Ministry>>> getDeletedMinistries() async {
    if (!await networkInfo.isConnected) {
      return const Left(
        NetworkFailure(
          message: 'No internet connection. Please check your network.',
        ),
      );
    }

    try {
      final ministries = await remoteDataSource.getDeletedMinistries();
      return Right(ministries);
    } on ServerException catch (e) {
      return Left(ServerFailure(message: e.message));
    } catch (e) {
      return const Left(
        ServerFailure(
          message: 'An unexpected error occurred. Please try again.',
        ),
      );
    }
  }

  @override
  Future<Either<Failure, Ministry>> restoreMinistry(String id) async {
    if (!await networkInfo.isConnected) {
      return const Left(
        NetworkFailure(
          message: 'No internet connection. Please check your network.',
        ),
      );
    }

    try {
      final ministry = await remoteDataSource.restoreMinistry(id);
      return Right(ministry);
    } on ServerException catch (e) {
      return Left(ServerFailure(message: e.message));
    } catch (e) {
      return const Left(
        ServerFailure(
          message: 'An unexpected error occurred. Please try again.',
        ),
      );
    }
  }

  @override
  Future<Either<Failure, void>> hardDeleteMinistry(String id) async {
    if (!await networkInfo.isConnected) {
      return const Left(
        NetworkFailure(
          message: 'No internet connection. Please check your network.',
        ),
      );
    }

    try {
      await remoteDataSource.hardDeleteMinistry(id);
      return const Right(null);
    } on ServerException catch (e) {
      return Left(ServerFailure(message: e.message));
    } catch (e) {
      return const Left(
        ServerFailure(
          message: 'An unexpected error occurred. Please try again.',
        ),
      );
    }
  }

  @override
  Future<Either<Failure, void>> resetMinistryPassword(
    String id,
    String newPassword,
  ) async {
    if (!await networkInfo.isConnected) {
      return const Left(
        NetworkFailure(
          message: 'No internet connection. Please check your network.',
        ),
      );
    }

    try {
      await remoteDataSource.resetMinistryPassword(id, newPassword);
      return const Right(null);
    } on ServerException catch (e) {
      return Left(ServerFailure(message: e.message));
    } catch (e) {
      return const Left(
        ServerFailure(
          message: 'An unexpected error occurred. Please try again.',
        ),
      );
    }
  }

  // ============================================
  // MINISTRY SELF-MANAGEMENT IMPLEMENTATIONS
  // ============================================

  @override
  Future<Either<Failure, Ministry>> getMyMinistry() async {
    if (!await networkInfo.isConnected) {
      return const Left(
        NetworkFailure(
          message: 'No internet connection. Please check your network.',
        ),
      );
    }

    try {
      final ministry = await remoteDataSource.getMyMinistry();
      return Right(ministry);
    } on ServerException catch (e) {
      return Left(ServerFailure(message: e.message));
    } catch (e) {
      return const Left(
        ServerFailure(
          message: 'An unexpected error occurred. Please try again.',
        ),
      );
    }
  }

  @override
  Future<Either<Failure, Ministry>> updateMyMinistry({
    String? description,
    String? phone,
    String? address,
    String? website,
    Uint8List? logoBytes,
    String? logoFileName,
  }) async {
    if (!await networkInfo.isConnected) {
      return const Left(
        NetworkFailure(
          message: 'No internet connection. Please check your network.',
        ),
      );
    }

    try {
      final ministry = await remoteDataSource.updateMyMinistry(
        description: description,
        phone: phone,
        address: address,
        website: website,
        logoBytes: logoBytes,
        logoFileName: logoFileName,
      );
      return Right(ministry);
    } on ServerException catch (e) {
      return Left(ServerFailure(message: e.message));
    } catch (e) {
      return const Left(
        ServerFailure(
          message: 'An unexpected error occurred. Please try again.',
        ),
      );
    }
  }
}
